### ISSUE TITLE
Namespace usage

### ISSUE THREAD

**Issue by aioue** [dpetzold/kube-resource-explorer#1]
Running against OpenShift 3.11.

Without the namespace param, I was getting just 'default' project stats.

`-namespace ""`

Gave me all pods across all namespaces. This isn't mentioned in the readme and is extremely useful.

**Comment by kotarusv** [comment]
+ 1 am hitting the same problem. scratching my head how to get stats from across all the projects. It is good to have single project but for admins it should give across all the projects also for capacity planning

**Comment by porridge** [comment]
The help message is actually wrong. It says:
```
$ docker run -it     -v${HOME}/.kube:/.kube     -v${HOME}/.config/gcloud:/.config/gcloud     -v/etc/ssl/certs:/etc/ssl/certs     dpetzold/kube-resource-explorer --help
Usage of /kube-resource-explorer:
[...]
  -namespace string
    	filter by namespace (defaults to all) (default "default")
```
